---
- hosts: localhost
  vars:
    orgid: 1
  tasks:
  - name: Call Satellite API to promote content
    uri:
      url: https://sat.example.com/katello/api/content_view_versions/incremental_update/
      validate_certs: no
      force_basic_auth: yes
      user: admin
      password: "{{ ansible_password }}"
      method: POST
      body_format: json
      body:
        content_view_version_environments:
          -
            content_view_version_id: "{{ cv_id | min }}"
            environment_ids: "{{ lc_id | unique }}"
        resolve_dependencies: 1
        add_content:
          errata_ids:
            - "{{ errata_id }}"
        updated_hosts[included]:
          - nil
