- hosts: localhost
  tasks:
  - name: Call Satellite API for errata info
    uri:
      url: "https://sat.example.com/katello/api/errata?cve={{ cve }}"
      validate_certs: no
      force_basic_auth: yes
      user: admin
      password: "{{ ansible_password }}"
    register: cveout

  - fail:
      msg: "No package available for CVE(s) {{ cve }}"
    when: "cveout.json.results[0].packages is not defined"

  - set_stats:
      aggregate: no
      data:
        pkglist: "{{ cveout.json.results[0].packages }}"
        errata_id: "{{ cveout.json.results[0].errata_id }}"
