# Note that host should be restricted to something with upstream access, or
# else you will get only info for available packages
- hosts: sat.example.com
  remote_user: root
  tasks:
  - name: Check for CVE patch
    # Have to use command because yum module isn't up to doing this
    command: /usr/bin/yum updateinfo list --cve "{{cve}}"
    args:
      warn: no
    register: cveout

  - set_fact: "pkglist={{ cveout.stdout | regex_findall('RHSA\\S+\\s+\\S+\\s+(\\S+)') }}"

  - name: Determine success
    fail:
      msg: "No package available for CVE(s) {{cve}}"
    when: "'RHSA' not in cveout.stdout"
