---
- name: "Display packages to be updated"
  debug:
    msg: "Updating {{ pkglist | join(' ') }}"

- name: "Update packages"
  yum:
    name: "{{ pkglist | join(',') }}"
    state: latest
  register: package_update
