---
- name: Install MariaDB
  yum:
    name: mariadb-server
    state: latest

- name: Install the Python MySQL Support Libraries
  yum:
    name: MySQL-python
    state: latest

- name : start mysql server and enable it
  service:
    name: mariadb
    state: started
    enabled: yes

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

- name: Create a New Test DB called MyNewDB
  mysql_db: name=MyNewDB state=present login_user=root login_password={{ mysql_root_password }}

- name: Set firewall policy for MariaDB
  firewalld:
    port: 3306/tcp
    immediate: true
    permanent: true
    state: enabled
